### PR TITLE
Make avformat lower priority for image sequences

### PR DESCRIPTION
**Pull request by bmatherly**
The avformat producer does not always exhibit the same behavior as
qimage and pixbuf.

Proposed workaround for https://github.com/mltframework/mlt/issues/543

### CODE REVIEW

**Comment by ddennedy** [comment]
They do not need to behave the same, avformat is faster, and avformat maintains a consistent frame rate independent of the consumer/profile frame rate.

**Comment by bmatherly** [comment]
> They do not need to behave the same

Ok. Perhaps that was a bad assumption on my part. The advantage of the loader services having the same behavior is that users will receive a similar experience regardless of what service is available on their system. Without consistent behavior, the services are not really interchangeable.

**Comment by ddennedy** [comment]
I agree with your point about consistency of interchangeable producers. But I would not be surprised if now someone is depending on the new behavior with an image sequence loaded with avformat and either default 25 fps or overridden with a `framerate` property. I do not care too strongly for Shotcut since we control it there (I might want to switch to avformat in the future).
However, I want to get @j-b-m or @vpinon opinion about this.

**Comment by ddennedy** [comment]
@jliljebl how would this affect Flowblade?

**Comment by bmatherly** [comment]
I agree we should check if anyone depends on the current behavior of avformat. If nobody is depending on it, I wonder if it could be changed to be similar to the others? Or, someone could possibly write a new image producer that is uses avformat under the hood in a way that is interchangeable. I might be available to do something like that if it would provide a performance improvement and would not hinder any applications depending on the current behavior.

**Comment by ddennedy** [comment]
I do not agree avformat image sequence behavior in MLT should be changed and made the same as the others for the way it handles frame rate can be preferable. For this reason, I reject this pull request as if agreed by others, I would rather revert b4c3978b7b63a735d3bb82aa55bca2787edd9a27

**Comment by ydesgagn** [comment]
Do you want to add a `-safe` command line option and read loader.safe instead of loader.dict in that case? That way both methods are preserved. On our side we can easily add that flag based on the scenario creation date.

**Comment by ddennedy** [comment]
@ydesgagn  no thank you

**Comment by ydesgagn** [comment]
Understood. Thanks for all this.

**Comment by ddennedy** [comment]
reverted b995dd0f instead

**Comment by jliljebl** [comment]
I just noticed this had a question for me. 

Reading this and the other thread I think I can't point to a behavioral difference that I would have noticed in this area, so reverting to earlier behavior is fine for me.

**Pull request closed without merging**
