### PR TITLE
fix mlt linux compile with ndi version 2017-01-06 @ r72018

### PR DESCRIPTION
**Pull request by walterav1984**
md5 9d1ebc495f603989cf0061a3d761b4f2  "NewTek NDI SDK (Linux).zip"

### CODE REVIEW

**Comment by max-verem** [comment]
LGTM

**Comment by walterav1984** [comment]
It does compile, but I don't know how to check if its working. The command melt -query consumer/producer doesn't list NDI as an option, that might be because of the missing yaml info pages for NDI.

**Comment by max-verem** [comment]
it listed:
```
[root@dev-5 mlt]# melt -query consumer
---
consumers:
  - xml
  - gtk2_preview
  - decklink
  - cbrts
  - ndi
  - multi
  - null
  - blipflash
  - avformat
  - sdi
...
```

and configure also notices it:
```
Configuring modules/ndi:
- NDI SDK found: enabling it
```

typically usage is:
```
melt -profile dv_pal BSQ21769.mov -consumer ndi:demo1
```

may be you forgot to specify configure options:
```
    --ndi-sdk-include=/usr/local/ndi/include \
    --ndi-sdk-lib=/usr/local/ndi/lib \
```

**Comment by walterav1984** [comment]
@max-verem 
Your output seems more successful, mine is still not working...

I copied the include & lib folders from the Newtek NDI SDK to src/modules/ndi/ than I copied x86_64-linux-gnu-5.4/libndi.so.1.0.1 to lib/libndi.so

As for compiling and testing mlt:
`
./configure --ndi-sdk-include=/home/test/mygitprojects/mlt/src/modules/ndi/include --ndi-sdk-lib=/home/test/mygitprojects/mlt/src/modules/ndi/lib
...
NDI SDK found: enabling it
...

make
source setenv
cd src/melt
./melt -query consumer/producer
`
This still doesn't mention NDI as consumer/producer, do you have the latest Newtek NDI SDK maybe they broke something or does your build work with recent SDK?

**Pull request merged**
