### PR TITLE
Add a loop range feature to MLT Producer

### PR DESCRIPTION
**Pull request by bmatherly**
This allows an application to request a producer loop between a start and end frame.

### CODE REVIEW

**Comment by ddennedy** [comment]
Is this redundant with the properties in, out, and eof?

**Comment by bmatherly** [comment]
> Is this redundant with the properties in, out, and eof?

I tried to start with a variation of in/out/eof. But I didn't think of a way to make it work. If you change in and out, you inherently change the length of the clip. It also changes the meaning of the frame number that you requested to be the loop point.

I am willing to try out some other ideas if you think of another way to accomplish this.

**Comment by ddennedy** [comment]
Do you still want to add this?

**Comment by bmatherly** [comment]
No longer needed

**Pull request closed without merging**
