### PR TITLE
Linsys: do not free null pointer

### PR DESCRIPTION
**Pull request by shlyakpavel**
This seems to be a dangerous copy-pasted line.
Refer issue https://github.com/mltframework/mlt/issues/392 part 1

### CODE REVIEW

**Comment by ddennedy** [comment]
free() accepts a null pointer. Explain more.

**Comment by shlyakpavel** [comment]
> free() accepts a null pointer. Explain more.

This is dangerous in terms of misunderstanding that might occur when changing the code. The pointer is ALWAYS null so it takes much time to understand that the free() is just a copy-paste, but not intended behavior

**Comment by bmatherly** [comment]
> If ptr is NULL, no operation is performed.

https://linux.die.net/man/3/free

Not a bug if the pointer was initialized to NULL. Theoretically there could be a bug if the pointer was never initialized or if it was previously freed and not re-initialized to NULL.

In the case of #392 part 1, consumer_SDIstream_s  is initialized with calloc(). So the pointer is initialized to NULL. And by inspection, I can't see a case where the pointer would be freed twice.

**Comment by ddennedy** [comment]
OK, reading this again in the context of the issue and full source, there is a simpler and more concrete explanation: the else block containing this line is only entered when the pointer is null; so the free() line does nothing. It's just that comments like "seems to be copy-paste" or "leads to misunderstanding" are not as concrete.

**Pull request merged**
