### PR TITLE
Fixed MLT CMake build on MSYS2

### PR DESCRIPTION
**Pull request by ice0**
[Synfig](https://github.com/synfig/synfig/) uses [MSYS2 ](https://www.msys2.org) to build Windows binaries. We added MLT package to MSYS2 (https://github.com/msys2/MINGW-packages/pull/6990), so here our changes to CMake required to build it in MSYS2 environment.

**CMake Changes:**

- [CMake] Added ability to set x86 architecture on x64 machine (use -DARCH=i686). Required to build 32-bit version of package.
- [CMake] Added explicit pangoft2 dependency (Implicitly added on Linux, required for building on MSYS2)
- [CMake] Replaced dlfcn-win32 dependency with dlfcn on MSYS2
- [CMake] dll.a files now properly installed to lib directory on MSYS2
- [CMake] Fixed luma compiling on MSYS2
- [CMake] Fixed SDL2 detection on MSYS2

### CODE REVIEW

**Review by ddennedy — APPROVED** [review]

**Comment by ddennedy** [comment]
This looks good to me, thanks! But I want @vpinon 's review since he contributed the CMake build and does most maintenance on it.

**Comment by vpinon** [comment]
Hello,
No problem to improve CMake build, and to my knowledge it is not used for any packaging yet, only for easier IDE integration by some devs...
So by now we will have to check not to break MSYS2 :smiley:
Thanks for your contribution!

**Comment by vpinon** [comment]
@ice0 I hope my latest commit mltframework@6e56b45 doesn't break your builds (goal is rather to make you benefit from improvements, making more features available)

**Comment by ice0** [comment]
No problem, I will check it later. Also I can add Appveyor CI for automatically building MSYS2 package, so you can know if something is broken.

**Pull request merged**
