### PR TITLE
Fix cracking sound with FLAC audio

### PR DESCRIPTION
**Pull request by bmatherly**
Account for samples already in the buffer when calculating PTS synchronization.

### CODE REVIEW

**Comment by tuffnerdstuff** [comment]
I tested your fix with my setup described in #741 and the audio is clear now!

**Comment by ddennedy** [comment]
The description is misleading because the change is not limited to FLAC. Since this affects everything with audio and especially audio/video synchronization this needs a lot of testing across a variety of inputs that stress seeking (multiple splits) while assessing sync. Also, needs paying attention to continuity of audio at clip split points.

**Comment by bmatherly** [comment]
> The description is misleading because the change is not limited to FLAC

I tried to make a change that was specific to FLAC but it was not sufficient.

> this needs a lot of testing

Agreed. And with this more accurate PTS calculation, I wonder if we want to tighten up the tolerances before we do all that testing. For example, maybe we want the ahead_threshold ot be in units of samples or seconds instead of video frames (since video frame duration changes based on frame rate which is why we get different results at different frame rates).

**Comment by ajyoon** [comment]
For what it's worth, I was going crazy trying to fix crackles and pops in kdenlive with WAV pcm s24le audio persistently appearing at clip boundaries in preview and renders, and this branch seems to have fixed it. Could be a coincidence though if this really is FLAC specific.

**Comment by ddennedy** [comment]
@ajyoon What were the sample rates of your WAV and that of the render output?

**Comment by ajyoon** [comment]
I'm working in 24bit signed WAV, which I think may have contributed to the bugs since [the kdenlive docs recommend 16bit](https://docs.kdenlive.org/en/troubleshooting/windows_issues.html#audio-pops-and-ticks-in-render)

**Comment by ddennedy** [comment]
@ajyoon Sample rate aka frequency, not sample format, please.

**Comment by ajyoon** [comment]
oh my bad - 48k (and 4 channels if that's relevant)

**Comment by ddennedy** [comment]
Yes, that helps a lot, thanks!

**Comment by ddennedy** [comment]
@bmatherly Since you wrote "I wonder if we want to tighten up the tolerances" I assume this PR is not ready to merge, but you did not create it as a draft PR. So, I added the pending label. Remove the pending label when you think it is ready, and in the future you can create a PR as a draft when it is a proposal and still testing. A draft PR shows a "Ready for Review" button you can click when it is really ready.

**Comment by bmatherly** [comment]
> Since you wrote "I wonder if we want to tighten up the tolerances" I assume this PR is not ready to merge, but you did not create it as a draft PR

This is good to go from my perspective. I only suggested tightening the tolerance, because from a math perspective, there is no reason that ahead_threshold could not be 1. But we would have to do a LOT of testing to have confidence in that.

This change will improve any audio format that has a packet duration that is 3 video frames or longer. In the case of 60fps video and 48kHz audio, one video frame is the duration of 800 audio samples. For FLAC, one audio packet is 4096 frames - That is more than 5 video frames. AC3 audio typically has 1536 samples per packet. So that is under the 3 frame threshold. I do not know the typical number of samples per packet for other formats.

**Pull request merged**
