### PR TITLE
Sliced interlaced-aware image convert implemented

### PR DESCRIPTION
**Pull request by max-verem**
This rework implement sliced interlace-aware pixel format convertor that should fix artifacts on interlaced 4:2:0 sources

Please do a tests if works properly

### CODE REVIEW

**Comment by bmatherly** [comment]
I understand that the code processes the picture in 10 slices. But the slices are not processed in separate threads. So what is the advantage to processing in slices?

**Comment by ddennedy** [comment]
@bmatherly I think he is just preparing for threaded processing by using a slice context and function while we wait to verify it fixes the bug.

**Comment by bmatherly** [comment]
Makes sense. I suppose we will also want to optimize the number of slices when the time comes.

**Comment by walterav1984** [comment]
It fixes chroma upsampling error :-D , but creates a new kind of field sync error ;-(.  Please see #172

**Comment by walterav1984** [comment]
I can confirm this looks Fixed!

**Pull request closed without merging**
