### PR TITLE
Vertical slices

### PR DESCRIPTION
**Pull request by max-verem**
Use vertical slices to fix https://github.com/mltframework/mlt/issues/172

### CODE REVIEW

**Comment by ddennedy** [comment]
According to the thread in #172 it sounds like this was not successful on NTSC. Should we consider to close this and merge #181 instead?

**Comment by walterav1984** [comment]
This pull request also fixes HD interlaced h264 4:2:0 chroma upsampling errors but freezes playback of HD h264 after around ~100 frames(might be CPU bound).  Please look for further debug info #166.

**Comment by walterav1984** [comment]
Freezing playback of HD h264 interlaced 1080i50 4:2:0 after ~100 frames is caused in commit fb09410.

Building and running melt commit 58d8ce does not show this behavior freezing behavior for HD h264 1080i50 4:2:0 footage.

**Comment by max-verem** [comment]
please provide a sample that reproduce freezing

**Pull request closed without merging**
