### PR TITLE
Add reorder function to mlt playlist.

### PR DESCRIPTION
**Pull request by bmatherly**
This change adds a function to allow a playlist to be arbitrarily reordered I would be open to discussion of other ways to accomplish this.

### CODE REVIEW

**Comment by ddennedy** [comment]
I feel like we should have unit tests for mlt_playlist/Mlt::Playlist. Are you up to adding at least one for this new method? It would exercise some other methods in the course of it.

**Comment by bmatherly** [comment]
> I feel like we should have unit tests for mlt_playlist/Mlt::Playlist. Are you up to adding at least one for this new method? It would exercise some other methods in the course of it.

Yes, I would be happy to add some unit tests. But before I do, could you comment on the general approach? I have some concern that it might be confusing. But I couldn't think of a better way. I had considered putting the sorting in the playlist class. For example, I could add a function mlt_playlist_sort_by_filedate(). But then a new function would have to be added every time an application wants to invent a new way to rearrange the list. 

If you are comfortable with the current approach, I'll put together some tests.

**Comment by ddennedy** [comment]
I like the general approach.

**Comment by bmatherly** [comment]
I added some tests for playlist. Let me know what you think.

**Pull request merged**
