### PR TITLE
Kdenlivetitle: Add ellipse item

### PR DESCRIPTION
**Pull request by jlskuz**

### CODE REVIEW

**Comment by jlskuz** [comment]
You can test this change with the attached file
[ellipse.kdenlivetitle.zip](https://github.com/mltframework/mlt/files/6134558/ellipse.kdenlivetitle.zip)
Or by creating a `*.kdenlivetitle` file with this content
```xml
<kdenlivetitle duration="125" LC_NUMERIC="C" width="1920" height="1080" out="125">
 <item type="QGraphicsEllipseItem" z-index="1">
  <position x="1217" y="261">
   <transform zoom="100">1,0,0,0,1,0,0,0,1</transform>
  </position>
  <content brushcolor="99,121,247,255" pencolor="255,44,83,255" penwidth="14" rect="0,0,156.698,267.326"/>
 </item>
 <item type="QGraphicsRectItem" z-index="1">
  <position x="130" y="261">
   <transform zoom="100">1,0,0,0,1,0,0,0,1</transform>
  </position>
  <content brushcolor="99,121,247,255" pencolor="255,44,83,255" penwidth="14" rect="0,0,156.698,267.326"/>
 </item>
 <startviewport rect="0,0,1920,1080"/>
 <endviewport rect="0,0,1920,1080"/>
 <background color="0,0,0,0"/>
</kdenlivetitle>
```

**Comment by ddennedy** [comment]
This looks fine to me, and I see you are now a regular Kdenlive contributor, which is great to see for that project! However, I would like to give another kdenlive developer the chance to agree with this since I do not have a DTD or schema to guide the decision. If I do not hear anything from one of them in a week or so, I will merge it.

**Comment by bmatherly** [comment]
My only comment is that this file has inconsistent whitespace. It would be great if someone would switch it to use all tabs like most files in this module (but not all, other files are also inconsistent, unfortunately)

**Comment by jlskuz** [comment]
I hope the whitespaces are good now?

**Comment by bmatherly** [comment]
Looks great Thanks for doing that!

**Review by j-b-m — APPROVED** [review]

**Pull request merged**
