### PR TITLE
Add function to disconnect all producers

### PR DESCRIPTION
**Pull request by alcinos**

### CODE REVIEW

**Comment by alcinos** [comment]
Which version number should I use ?

**Comment by ddennedy** [comment]
MLT_6.6.0 and MLTPP_6.6.0 (these are the next release versions)

**Comment by ddennedy** [comment]
I approve now.

**Comment by alcinos** [comment]
I've changed logic a bit because the disconnection of the consumer done in disconnect_producer was an unwanted side-effect

**Pull request merged**
